### ISSUE TITLE
exception thrown 'newtonsoft.json.jsonreaderexception' in system.private.corelib.dll

### ISSUE THREAD

**Issue by Justsomeotakuu** [Xwilarg/NHentaiSharp#6]
i dont know what causes it

**Comment by Xwilarg** [comment]
I don't think the library is working anymore due to the website putting a anti-bot protection over their API

**Comment by Justsomeotakuu** [comment]
oh damn well that sucks, thanks for responding so fast tho
do you think it will work sometime again?

**Comment by Justsomeotakuu** [comment]
oops

**Comment by Xwilarg** [comment]
I have no idea, I tried contacting the dev of the website but he never answered me, I think there are very low chances

**Comment by Justsomeotakuu** [comment]
alright thanks
